### ISSUE TITLE
After searching for a note, note is not opening.

### ISSUE THREAD

**Issue by middo1** [rubbieKelvin/notes#108] opened 2023-02-17 23:53 UTC
Also after searching and refreshing the results is still showing.![Screenshot_20230218-005408.jpg](https://user-images.githubusercontent.com/56052889/219818300-3619a94d-429c-416a-af09-4e197270285a.jpg)

**Comment by middo1** [comment] 2023-02-17 23:59
Sorry I can't help 🤧

**Comment by rubbieKelvin** [comment] 2023-02-18 01:54
duplicate of #98

**Closed** 2023-02-18 01:53 UTC
Labels: duplicate
